### ISSUE TITLE
Save receipt root in elasticsearch 

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/telosevm-es-indexer#10]
## Overview

Currently, the receipt root is being thrown away. We would like to save it in elasticsearch so we don't have to calculate it again.

## Acceptance criteria

- The receipt root should be saved `elasticsearch`

**Comment by guilledk** [comment]
Done in https://github.com/telosnetwork/telosevm-es-indexer/commit/453056f269d19b12e80780941b9b7ecec6aa4e4e
