### ISSUE TITLE
[Testnet] Invalid raw EVM transaction crashing deserializer

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/telosevm-es-indexer#5]
## Overview

The smart contract allows an invalid transaction to go through and this causes the deserializer to crash.

####### Block Hash
`0AB535E430FF536FFC87C848E688FA0E28E48BB089F48493F636A866E9916A84`
 
###### Raw EVM transaction
`f901481985746050fb56831e8480949a469d1e668425907548228ea525a661ff3bfa2b80b90124b069bcc30000000000000000000000000000000000000000000000000000000000000060000000000000000000000000111111111111111111111111111111111111111100000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000043300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000220000000000000000000000000000003000000000000000000000000000000000`

## Steps to reproduce

1. Identify the transaction on block `0AB535E430FF536FFC87C848E688FA0E28E48BB089F48493F636A866E9916A84`
2. See deserializer crashed

## Expected behavior

The transaction should not be accepted by the smart contract.
The deserializer should not crash.

**Comment by guilledk** [comment]
This was fixed on #8
